[package]
name = "subsquid-network-transport"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "node"
path = "src/node.rs"

[[bin]]
name = "bootnode"
path = "src/bootnode.rs"

[[bin]]
name = "grpc-client"
path = "src/grpc-client.rs"

[[bin]]
name = "keygen"
path = "src/keygen.rs"

[features]
worker = ["cmake", "cxx", "cxx-build"]

[dependencies]
anyhow = "1"
async-trait = "0.1"
bimap = "0.6"
clap = { version = "4", features = ["derive", "env"] }
env_logger = "0.10"
futures = "0.3"
futures-core = "0.3"
libp2p = { version = "0.52", features = ["autonat", "dns", "tcp", "tokio", "websocket", "noise", "yamux", "identify", "kad", "autonat", "relay", "dcutr", "ping", "request-response", "gossipsub"] }
libp2p-swarm-derive = "0.33"
log = "0.4"
rand = "0.8"
snow = "^0.9.1"
thiserror = "1"
tokio = { version = "1", features = ["fs", "macros", "rt-multi-thread", "sync"] }
tokio-stream = { version  = "0.1", features = ["sync"] }
tokio-util = { version = "0.7", features = ["compat", "codec"] }

# Worker
cxx = {version = "1", optional = true }

# RPC
prost = "0.12"
tonic = { version = "0.10", features = ["gzip"] }
tower = { version = "0.4", features = ["make"] }

[build-dependencies]
# Worker
cmake = { version = "0.1", optional = true }
cxx-build = { version =  "1", optional = true }

# RPC
tonic-build = "0.10"
