name: docker
on:
  workflow_dispatch: # manually run
    inputs:
      tag:
        description: image tag
        required: true

env:
  CI: true

jobs:
  publish:
    name: docker-publish
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & publish bootnode
        uses: docker/build-push-action@v3
        with:
          context: ./transport
          target: bootnode
          push: true
          tags: subsquid/bootnode:${{ inputs.tag }}

      - name: Build & publish rpc-node
        uses: docker/build-push-action@v3
        with:
          context: ./transport
          target: rpc-node
          push: true
          tags: subsquid/bootnode:${{ inputs.tag }}
